### ISSUE TITLE
Editing an image using an external app rewrites the original copy of the file

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#218]
Having the option to edit an image is good but what if the user wants to retain the original copy and make a duplicate? Right now, we rewrite the original image and there is no way to restore the original image afterwards, as far as I understood.

We could do one of the following to resolve this:
- leave it to the user to make a duplicate themselves before navigating to the external application 
- before navigating to the external app, we ask if they want to modify the original image or create a new image

**Comment by kirillt** [comment]
Actually, this isn't done by ARK Navigator. Editing is possible with any editor, but right now we have [ARK Retouch](https://github.com/ARK-Builders/ark-retouch/) which passes saved path back to Navigator app. It has "overwrite" checkbox, but it is switched off by default.

Preferred way, in fact, is not overwriting but creating new version of the resource, because we will track versions in the future: #40 Versions of a resource must grouped: only last version is displayed but also counter of versions should be presented to the user, the counter should be unfoldable into list of versions.

**Comment by melvin4u445** [comment]
Okay, that sounds good! Let's close this ticket :)
